# $NetBSD$

COMMENT = Katana Desktop Environment

SUBDIR += ariya-icons
SUBDIR += libdbusmenu-katie
SUBDIR += poppler-katie
SUBDIR += qca-katie
SUBDIR += strigi
SUBDIR += attica-katie
SUBDIR += kde-baseapps
SUBDIR += kde-extraapps
SUBDIR += kde-workspace
SUBDIR += kdelibs

.include "../mk/misc/category.mk"
