# $NetBSD$

COMMENT = Katana Desktop Environment

SUBDIR += ariya-icons
SUBDIR += attica-katie
SUBDIR += kde-baseapps
SUBDIR += kde-workspace
SUBDIR += kdelibs
SUBDIR += libdbusmenu-katie
SUBDIR += strigi

.include "../mk/misc/category.mk"

